routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\PushServiceController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\Backend\AdminArticleController;
use App\Http\Controllers\Backend\AdminChangeController;
use App\Http\Controllers\Backend\AdminCommentController;
use App\Http\Controllers\Backend\AdminMailController;
use App\Http\Controllers\Backend\AdminNoticeController;
use App\Http\Controllers\Backend\AdminReportController;
use App\Http\Controllers\Backend\AdminRoleController;
use App\Http\Controllers\Backend\AdminSectionController;
use App\Http\Controllers\Backend\AdminTagController;
use App\Http\Controllers\Backend\AdminUserController;

Auth::routes();
Route::get('/websocket', function () {
    event(new \App\Events\SomethingHappens('WebSocket connection enabled'));
});
Route::get('/cache', function () {
    $data = Cache::putMany([
        'apple' => 'Apple, Inc.',
        'microsoft' => 'Microsoft Corporation',
    ], 3600);
    echo Cache::get('apple') . '<br>' . Cache::get('microsoft');
});
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::resource('/articles', ArticleController::class, ['names' => 'articles']);
Route::get('/tags/{tag}', [TagsController::class, 'index'])->name('tags');
Route::any('/articles/{article}/comment', [CommentController::class, 'addToArticle'])->name('articles.comment');
Route::resource('/notices', NoticeController::class, ['names' => 'notices']);
Route::any('/notices/{notice}/comment', [CommentController::class, 'addToNotice'])->name('notices.comment');
Route::get('/contact', [MailController::class, 'contact'])->name('contact');
Route::post('/mail/send', [MailController::class, 'send'])->name('send');
Route::get('/admin/reports/index', [AdminReportController::class, 'index'])->name('backend.reports');
Route::post('/admin/reports/send', [AdminReportController::class, 'send'])->name('backend.report');
Route::resource('/admin/articles', AdminArticleController::class, ['names' => 'admin.articles']);
Route::resource('/admin/changes', AdminChangeController::class, ['names' => 'admin.changes']);
Route::resource('/admin/comments', AdminCommentController::class, ['names' => 'admin.comments']);
Route::resource('/admin/mails', AdminMailController::class, ['names' => 'admin.mails']);
Route::resource('/admin/notices', AdminNoticeController::class, ['names' => 'admin.notices']);
Route::resource('/admin/roles', AdminRoleController::class, ['names' => 'admin.roles']);
Route::resource('/admin/sections', AdminSectionController::class, ['names' => 'admin.sections']);
Route::resource('/admin/tags', AdminTagController::class, ['names' => 'admin.tags']);
Route::resource('/admin/users', AdminUserController::class, ['names' => 'admin.users']);
Route::get('/service', [PushServiceController::class, 'form'])->name('pushall.form');
Route::post('/service', [PushServiceController::class, 'send'])->name('pushall.send');

resources/views/about.blade.php
@extends('layouts.app')

@section('content')

<p align='center' class="lead text-muted"><img style="width:18%;position:relative;" src='/favicon.png'></p>
<h2 align='center' class="jumbotron-heading">About Us</h2>
<p align='center' class="lead text-muted">This is a working Laravel website written on PHP and using MySQL database interface, with many additional components included in a framework extending website functionality. The project is intended only for educational purposes. You can improve its source code if you need.</p>

@endsection

resources/views/articles-create.blade.php
@extends('layouts.app')

@section('content')

<h2 align='center' class="jumbotron-heading">Create Article</h2>

@include('form.check')

<form action="{{ route('articles.store') }}" method="POST">
@csrf

@include('form.create')

<p align='center'>
<input type='submit' name='submit' style="width:50%;" value="Post Article">
</p>
</form>

@endsection

resources/views/articles-edit.blade.php
@extends('layouts.app')

@section('content')

<h2 align='center' class="jumbotron-heading">Update Article</h2>

@include('form.check')

@can('update', $article)
<form action="{{ route('articles.update', ['article' => $article->slug]) }}" method="POST">
    {{ method_field('PATCH') }}
    {{ csrf_field() }}

@include('form.edit.article')

<p align='center'>
	<input type='submit' name='submit' style="width:25%;" value="Update Article">
</p>
</form>
@endcan

<article-update article-id="{{ $article->id }}"></article-update>

<form action="{{ route('articles.destroy', ['article' => $article->slug]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
	<p align='center'>
		<input type='submit' style="width:25%;" value="Delete Article">
	</p>
</form>

@endsection

resources/views/articles-show.blade.php
@extends('layouts.app')

@section('content')

    <h2 align='center' class="jumbotron-heading">{{ $article->title }}</h2>
    <p align='center' class="lead text-muted">{{ $article->date }}</p>
    @include('form.tags', ['tags' => $article->tags])
    <p align='center' class="lead text-muted">
        <a href="{{ route('articles.index') }}">Go Back</a>
    </p>
    <p align='center' class="lead text-muted">
        <img width="85%" src="{{ $article->img }}">
    </p>
    </section>
    <div class="container">
        <p class="lead text-muted">{{ $article->content }}</p>
    </div>
    <div class="container">

        @include('form.comment.article')

        @if (!empty($comments))

        @foreach ($comments as $comment)
            <p class="badge-secondary">{{ $comment->owner()->where('id', $comment->owner_id)->first()->name }} ({{ $comment->date }})</p>
            <p class="lead text-muted">{{ $comment->content }}</p>
        @endforeach

        {{ $comments->links() }}

        @endif
        
    </div>

@endsection

resources/views/articles-tags.blade.php
@php
    $tags = $tags ?? collect();
@endphp

@if ($tags->isNotEmpty())
  <div>
    <p align='center'>
      @foreach ($tags as $tag)
        <a href="{{ route('tag', ['tag' => $tag->name]) }}" class='badge badge-secondary'>{{ $tag->name }}</a>
      @endforeach
    </p>
    </div>
@endif

resources/views/contact.blade.php
@extends('layouts.app')

@section('content')

<h2 align='center' class="jumbotron-heading">Contact Us</h2>
@if ($errors->all())
	<div class="alert alert-danger">
		@foreach($errors->all() as $error)
		    <p>{{ $error }}</p>
		@endforeach
	</div>
@endif
<form action="{{ route('send') }}" method="POST">
@csrf
<p align='center'>
<input type='text' name='email' style="width:50%;" placeholder="Your email address..." value="{{ old('email') }}">
</p>
<p align='center'>
<textarea name='message' style="width:50%;height:20%;" placeholder="What's on your mind?" rows=4>{{ old('message') }}</textarea>
</p>
<p align='center'>
<input type='hidden' name='received' style="width:50%;" placeholder="Current timestamp..." value="{{ date('Y-m-d H:i:s') }}">
</p>
<p align='center'>
<input type='submit' name='submit' style="width:50%;" value="Send Message">
</p>
</form>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/menu.blade.php
<a href="{{ route('home') }}" class="navbar-brand d-flex align-items-center">Home</a>
<a href="{{ route('articles.index') }}" class="navbar-brand d-flex align-items-center">Posts</a>
<a href="{{ route('notices.index') }}" class="navbar-brand d-flex align-items-center">News</a>
<a href="{{ route('articles.create') }}" class="navbar-brand d-flex align-items-center">Compose</a>
<a href="{{ route('pushall.form') }}" class="navbar-brand d-flex align-items-center">Notify</a>
<a href="{{ route('contact') }}" class="navbar-brand d-flex align-items-center">Support</a>

@admin
<a href="{{ route('admin.sections.index') }}" class="navbar-brand d-flex align-items-center">Admin</a>
<a href="/telescope" class="navbar-brand d-flex align-items-center">Telescope</a>
@endadmin

<a href="{{ route('about') }}" class="navbar-brand d-flex align-items-center">About</a>

resources/views/news-show.blade.php
@extends('layouts.app')

@section('content')

    <h2 align='center' class="jumbotron-heading">{{ $notice->title }}</h2>
    <p align='center' class="lead text-muted">{{ $notice->date }}</p>
    @include('form.tags', ['tags' => $notice->tags])
    <p align='center' class="lead text-muted">
        <a href="{{ route('notices.index') }}">Go Back</a>
    </p>
    <p align='center' class="lead text-muted">
        <img width="85%" src="{{ $notice->img }}">
    </p>
    </section>
    <div class="container">
        <p class="lead text-muted">{{ $notice->content }}</p>
    </div>
    <div class="container">

        @include('form.comment.notice')

        @if (!empty($comments))

        @foreach ($comments as $comment)
            <p class="badge-secondary">{{ $comment->owner()->where('id', $comment->owner_id)->first()->name }} ({{ $comment->date }})</p>
            <p class="lead text-muted">{{ $comment->content }}</p>
        @endforeach

        {{ $comments->links() }}

        @endif
        
    </div>

@endsection

resources/views/news.blade.php
@extends('layouts.app')

@section('content')

  <div class="row">
    @foreach ($notices ?? '' as $notice)
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" src="{{ $notice->img }}" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">
              <b>{{ $notice->title }}</b>
              @include('form.tags', ['tags' => $notice->tags])
            </p>
            <p class="card-text">{{ $notice->description }}</p>
          </div>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a href="{{ route('notices.show', ['notice' => $notice->slug]) }}">View</a>
            </div>
            <div class="btn-group">
              <a href="{{ route('notices.edit', ['notice' => $notice->slug]) }}">Edit</a>
            </div>
            <div class="btn-group">
              <small class="text-muted"><p class="card-text">{{ $notice->date }}</p></small>
            </div>
          </div>
        </div>
      </div>
    @endforeach
    
    {{ $notices->links() }}
  </div>

@endsection

resources/views/notices-create.blade.php
@extends('layouts.app')

@section('content')

<h2 align='center' class="jumbotron-heading">Create News Article</h2>

@include('form.check')

<form action="{{ route('notices.store') }}" method="POST">
@csrf

@include('form.create')

<p align='center'>
<input type='submit' name='submit' style="width:50%;" value="Post Article">
</p>
</form>

@endsection

resources/views/notices-edit.blade.php
@extends('layouts.app')

@section('content')

<h2 align='center' class="jumbotron-heading">Update News Article</h2>

@include('form.check')

<form action="{{ route('notices.update', ['notice' => $notice->slug]) }}" method="POST">
    {{ method_field('PATCH') }}
    {{ csrf_field() }}

@include('form.edit.notice')

<p align='center'>
<input type='submit' name='submit' style="width:25%;" value="Update Article">
</p>
</form>
<form action="{{ route('notices.destroy', ['notice' => $notice->slug]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
	<p align='center'>
		<input type='submit' style="width:25%;" value="Delete Article">
	</p>
</form>

@endsection

resources/views/service.blade.php
@extends('layouts.app')

@section('content')

<h2 align='center' class="jumbotron-heading">Send Notification</h2>

@include('form.check')

<form action="{{ route('pushall.send') }}" method="POST">
@csrf

<p align='center'>
<input type='text' name='title' value="{{ old('title') }}" style="width:50%;" placeholder="Enter the notification title...">
</p>
<p align='center'>
<textarea name='text' style="width:50%;height:20%;" placeholder="What's on your mind?" rows=4>{{ old('text') }}</textarea>
</p>

<p align='center'>
<input type='submit' name='submit' style="width:50%;" value="Send">
</p>
</form>
</p>

@endsection