routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\PushServiceController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\Backend\AdminArticleController;
use App\Http\Controllers\Backend\AdminChangeController;
use App\Http\Controllers\Backend\AdminCommentController;
use App\Http\Controllers\Backend\AdminMailController;
use App\Http\Controllers\Backend\AdminNoticeController;
use App\Http\Controllers\Backend\AdminReportController;
use App\Http\Controllers\Backend\AdminRoleController;
use App\Http\Controllers\Backend\AdminSectionController;
use App\Http\Controllers\Backend\AdminTagController;
use App\Http\Controllers\Backend\AdminUserController;

Auth::routes();
Route::get('/websocket', function () {
    event(new \App\Events\SomethingHappens('WebSocket connection enabled'));
});
Route::get('/cache', function () {
    $data = Cache::putMany([
        'apple' => 'Apple, Inc.',
        'microsoft' => 'Microsoft Corporation',
    ], 3600);
    echo Cache::get('apple') . '<br>' . Cache::get('microsoft');
});
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::resource('/articles', ArticleController::class, ['names' => 'articles']);
Route::get('/tags/{tag}', [TagsController::class, 'index'])->name('tags');
Route::any('/articles/{article}/comment', [CommentController::class, 'addToArticle'])->name('articles.comment');
Route::resource('/notices', NoticeController::class, ['names' => 'notices']);
Route::any('/notices/{notice}/comment', [CommentController::class, 'addToNotice'])->name('notices.comment');
Route::get('/contact', [MailController::class, 'contact'])->name('contact');
Route::post('/mail/send', [MailController::class, 'send'])->name('send');
Route::get('/admin/reports/index', [AdminReportController::class, 'index'])->name('backend.reports');
Route::post('/admin/reports/send', [AdminReportController::class, 'send'])->name('backend.report');
Route::resource('/admin/articles', AdminArticleController::class, ['names' => 'admin.articles']);
Route::resource('/admin/changes', AdminChangeController::class, ['names' => 'admin.changes']);
Route::resource('/admin/comments', AdminCommentController::class, ['names' => 'admin.comments']);
Route::resource('/admin/mails', AdminMailController::class, ['names' => 'admin.mails']);
Route::resource('/admin/notices', AdminNoticeController::class, ['names' => 'admin.notices']);
Route::resource('/admin/roles', AdminRoleController::class, ['names' => 'admin.roles']);
Route::resource('/admin/sections', AdminSectionController::class, ['names' => 'admin.sections']);
Route::resource('/admin/tags', AdminTagController::class, ['names' => 'admin.tags']);
Route::resource('/admin/users', AdminUserController::class, ['names' => 'admin.users']);
Route::get('/service', [PushServiceController::class, 'form'])->name('pushall.form');
Route::post('/service', [PushServiceController::class, 'send'])->name('pushall.send');

app/Http/Controllers/Backend/AdminArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Article;

class AdminArticleController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Article::class, 'article');
    }

    public function index()
    {
        $articles = Article::with('tags')->orderBy('owner_id', 'ASC')->simplePaginate(20);

        return view('backend.articles', ['articles' => $articles]);
    }

    public function destroy(Article $article)
    {
        $article->delete();

        return redirect()->route('admin.articles.index');
    }
}

app/Http/Controllers/Backend/AdminChangeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Change;

class AdminChangeController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $changes = Change::orderBy('date', 'DESC')->get();

        return view('backend.changes', ['changes' => $changes]);
    }

    public function destroy(Change $change)
    {
        $change->delete();

        return redirect()->route('admin.changes.index');
    }
}

app/Http/Controllers/Backend/AdminCommentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Comment;

class AdminCommentController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $comments = Comment::orderBy('owner_id', 'ASC')->simplePaginate(20);

        return view('backend.comments', ['comments' => $comments]);
    }

    public function destroy(Comment $comment)
    {
        $comment->delete();

        return redirect()->route('admin.comments.index');
    }
}

app/Http/Controllers/Backend/AdminMailController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Mail;

class AdminMailController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Mail::class, 'mail');
    }

    public function index()
    {
        $mails = Mail::orderBy('received', 'DESC')->get();

        return view('backend.mails', ['mails' => $mails]);
    }

    public function destroy(Mail $mail)
    {
        $mail->delete();

        return redirect()->route('admin.mails.index');
    }
}

app/Http/Controllers/Backend/AdminNoticeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Notice;

class AdminNoticeController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */

    public function index()
    {
        $notices = Notice::orderBy('date', 'ASC')->simplePaginate(20);

        return view('backend.notices', ['notices' => $notices]);
    }

    public function destroy(Notice $notice)
    {
        $notice->delete();

        return redirect()->route('admin.notices.index');
    }
}

app/Http/Controllers/Backend/AdminReportController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class AdminReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('backend.reports');
    }

    public function send(Request $request)
    {
        $data = $request->input('reports');

        \App\Jobs\WebsiteReport::dispatch($data);

        return view('backend.reports');
    }
}

app/Http/Controllers/Backend/AdminRoleController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Role;

class AdminRoleController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Role::class, 'role');
    }

    public function index()
    {
        $roles = Role::orderBy('id', 'ASC')->get();

        return view('backend.roles', ['roles' => $roles]);
    }

    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('admin.roles.index');
    }
}

app/Http/Controllers/Backend/AdminSectionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Section;

class AdminSectionController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Section::class, 'section');
    }

    public function index()
    {
        $sections = Section::orderBy('name', 'ASC')->get();

        return view('backend.dashboard', ['sections' => $sections]);
    }

    public function destroy(Section $section)
    {
        $section->delete();

        return redirect()->route('admin.sections.index');
    }
}

app/Http/Controllers/Backend/AdminTagController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\Tag;

class AdminTagController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Tag::class, 'tag');
    }

    public function index()
    {
        $tags = Tag::orderBy('name', 'ASC')->get();

        return view('backend.tags', ['tags' => $tags]);
    }

    public function destroy(Tag $tag)
    {
        $tag->delete();

        return redirect()->route('admin.tags.index');
    }
}

app/Http/Controllers/Backend/AdminUserController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

use App\Models\User;

class AdminUserController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(User::class, 'user');
    }

    public function index()
    {
        $users = User::orderBy('email', 'ASC')->get();

        return view('backend.users', ['users' => $users]);
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/backend/articles.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Article Index</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">Symbolic Name</th>
<th style="width:40%;">Title</th>
<th style="width:10%;">Date</th>
<th style="width:8%;">Owner</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
{{ $articles->links() }}
@foreach ($articles as $article)
<tr>
<td>{{ $article->slug }}</td>
<td>{{ $article->title }}</td>
<td>{{ $article->date }}</td>
<td>{{ $article->owner()->where('id', $article->owner_id)->first()->name }}</td>
<form action="{{ route('admin.articles.destroy', ['article' => $article->slug]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/changes.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Changes Log</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">Author</th>
<th style="width:10%;">Date</th>
<th style="width:30%;">Article</th>
<th style="width:40%;">Fields</th>
</thead>
<tbody>
@foreach ($changes as $change)
<tr>
<td>{{ $change->author()->where('id', $change->author_id)->first()->name }}</td>
<td>{{ $change->date }}</td>
<td>{{ $change->article()->where('id', $change->article_id)->first()->title }}</td>
<td>{{ $change->fields }}</td>
<form action="{{ route('admin.changes.destroy', ['change' => $change->id]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/comments.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">User Comments</h2>
<table style="width:95%;">
<thead>
<th style="width:40%;">Content</th>
<th style="width:10%;">Date</th>
<th style="width:8%;">Owner</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
{{ $comments->links() }}
@foreach ($comments as $comment)
<tr>
<td>{{ $comment->content }}</td>
<td>{{ $comment->date }}</td>
<td>{{ $comment->owner()->where('id', $comment->owner_id)->first()->name }}</td>
<form action="{{ route('admin.comments.destroy', ['comment' => $comment->id]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/dashboard.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Admin Dashboard</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">Section</th>
<th style="width:40%;">Description</th>
<th style="width:10%;">Link</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
@foreach ($sections as $section)
<tr>
<td>{{ $section->name }}</td>
<td>{{ $section->description }}</td>
<td><a href="{{ route($section->uri, []) }}">{{ $section->uri }}</a></td>
<form action="{{ route('admin.sections.destroy', ['section' => $section->name]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/mails.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Mailing List</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">Email</th>
<th style="width:40%;">Message</th>
<th style="width:10%;">Received</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
@foreach ($mails as $mail)
<tr>
<td>{{ $mail->email }}</td>
<td>{{ $mail->message }}</td>
<td>{{ $mail->received }}</td>
<form action="{{ route('admin.mails.destroy', ['mail' => $mail->email]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/notices.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Notices Index</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">Symbolic Name</th>
<th style="width:40%;">Title</th>
<th style="width:10%;">Date</th>
<th style="width:8%;">Owner</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
{{ $notices->links() }}
@foreach ($notices as $notice)
<tr>
<td>{{ $notice->slug }}</td>
<td>{{ $notice->title }}</td>
<td>{{ $notice->date }}</td>
<td>{{ $notice->owner()->where('id', $notice->owner_id)->first()->name }}</td>
<form action="{{ route('admin.notices.destroy', ['notice' => $notice->slug]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/reports.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Website Reports</h2>
    
<form action="{{ route('backend.report') }}" method='POST'>
    {{ method_field('POST') }}
    {{ csrf_field() }}
<p align='center'>
<select id='reports' multiple='multiple' name='reports[]' style="width:30%;">
    <option value='articles'>Articles</option>
    <option value='changes'>Changes</option>
    <option value='comments'>Comments</option>
    <option value='mails'>Mail Queue</option>
    <option value='notices'>News Feed</option>
    <option value='roles'>Roles</option>
    <option value='tags'>Tags</option>
    <option value='users'>Users</option>
</select>
</p>
<p align='center'>
<input type='submit' name='submit' value='Generate Report'>
</p>
</form>

<p align='center'>{{ $result ?? '' }}</p>

@endadmin

@endsection

resources/views/backend/roles.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">User Roles</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">ID</th>
<th style="width:40%;">Name</th>
<th style="width:40%;">Description</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
@foreach ($roles as $role)
<tr>
<td>{{ $role->id }}</td>
<td>{{ ucfirst($role->name) }}</td>
<td>{{ $role->description }}</td>
<form action="{{ route('admin.roles.destroy', ['role' => $role->name]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/tags.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">Article Tags</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">ID</th>
<th style="width:40%;">Name</th>
<th style="width:10%;">Actions</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
@foreach ($tags as $tag)
<tr>
<td>{{ $tag->id }}</td>
<td>{{ $tag->name }}</td>
<form action="{{ route('admin.tags.destroy', ['tag' => $tag->name]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection

resources/views/backend/users.blade.php
@extends('layouts.app')

@section('content')

@admin

<h2 align='center' class="jumbotron-heading">User Accounts</h2>
<table style="width:95%;">
<thead>
<th style="width:20%;">Username</th>
<th style="width:40%;">Email</th>
<th style="width:10%;">Role</th>
<th style="width:8%;">Actions</th>
</thead>
<tbody>
@foreach ($users as $user)
<tr>
<td>{{ $user->name }}</td>
<td>{{ $user->email }}</td>
<td>{{ ucfirst($user->role()->where('id', $user->role_id)->first()->name) }}</td>
<form action="{{ route('admin.users.destroy', ['user' => $user->email]) }}" method="POST">
	{{ method_field('DELETE') }}
	{{ csrf_field() }}
    <td><input type='submit' value="X"></td>
</form>
</tr>
@endforeach
</tbody>
</table>

@endadmin

@endsection